# Generated by Django 5.2.3 on 2025-07-03 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer'), ('both', 'Both')], max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('fullname', models.CharField(max_length=200)),
                ('profilepic', models.URLField(blank=True, default='https://res.cloudinary.com/dmebvno0m/image/upload/v1749882603/veilzulxlqv2tjk1ncgs.jpg', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('work_experience', models.JSONField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_site', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
