# Generated by Django 5.2.3 on 2025-07-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='languages',
            field=models.JSONField(blank=True, help_text='these is trail2', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_experience',
            field=models.JSONField(blank=True, help_text='these is trail2', null=True),
        ),
    ]
