# Generated by Django 5.2.3 on 2025-07-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_languages_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
