# Generated by Django 5.2.3 on 2025-07-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Gig',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
