# Generated by Django 5.2.3 on 2025-07-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
