# Generated by Django 5.2.3 on 2025-07-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='client',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Gig',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
