# Generated by Django 5.2.3 on 2025-07-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='client',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Gig',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
