# Generated by Django 5.2.3 on 2025-07-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinvitation',
            name='group',
        ),
        migrations.DeleteModel(
            name='FreelancerGroup',
        ),
        migrations.DeleteModel(
            name='GroupInvitation',
        ),
    ]
