# Generated by Django 5.2.3 on 2025-08-11 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_groupinvitation_group_delete_freelancergroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='job',
            name='client',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Gig',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
