# Generated by Django 5.2.3 on 2025-08-16 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_application_group_groupinvite_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancegroup',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='freelancegroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_group',
        ),
        migrations.RemoveField(
            model_name='groupinvite',
            name='group',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='groupinvite',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='groupinvite',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_invite',
        ),
        migrations.RemoveField(
            model_name='job',
            name='client',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='FreelanceGroup',
        ),
        migrations.DeleteModel(
            name='Gig',
        ),
        migrations.DeleteModel(
            name='GroupInvite',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
