# Generated by Django 5.2.3 on 2025-08-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='is_individual',
            field=models.BooleanField(default=True),
        ),
    ]
