# Generated by Django 5.2.3 on 2025-08-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_application_is_group_application_is_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='leader_of',
            field=models.JSONField(default=list),
        ),
    ]
