# Generated by Django 5.2.3 on 2025-08-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_freelancegroup_name_gigapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GigApplication',
        ),
    ]
