# Generated by Django 5.2.3 on 2025-08-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_userprofile_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
