# Generated by Django 5.2.3 on 2025-08-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_userprofile_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancegroup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('hired', 'Hired')], default='pending', max_length=20),
        ),
    ]
