# Generated by Django 5.2.3 on 2025-08-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_freelancegroup_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancegroup',
            name='status',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('hired', 'Hired')], default='pending', max_length=20),
        ),
    ]
