# Generated by Django 5.2.3 on 2025-08-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_remove_conversation_created_at_and_more'),
        ('users', '0029_remove_freelancegroup_status_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to='users.userprofile'),
        ),
    ]
