# Generated by Django 5.2.3 on 2025-08-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobstatus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='is_gig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='is_job',
            field=models.BooleanField(default=False),
        ),
    ]
