# Generated by Django 5.2.3 on 2025-08-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobstatus', '0002_jobstatus_is_draft_jobstatus_is_gig_jobstatus_is_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
