# Generated by Django 5.2.3 on 2025-08-18 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobstatus', '0003_jobstatus_price'),
        ('users', '0027_alter_userprofile_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatus',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.application'),
        ),
    ]
