# Generated by Django 5.2.3 on 2025-08-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobstatus', '0004_alter_jobstatus_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='submission_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='submitted_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
