# Generated by Django 5.2.3 on 2025-08-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobstatus', '0005_jobstatus_submission_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatus',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('Submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='ongoing', max_length=20),
        ),
    ]
